### ISSUE TITLE
4.0.0 router can't use `/` inside of an iframe

### ISSUE THREAD

**Issue by johnlindquist** [choojs/choo#344] opened 2016-11-28 17:07 UTC
4.0:
http://plnkr.co/edit/HsO6Dwtv1L4CDYi10Gv9?p=preview

3.0:
http://plnkr.co/edit/KSLgxEQveieLKWo5okxt?p=preview

In 3.0, `choo` properly detected the "base" route inside an iframe as `/`. Now in 4.0, it's forcing me to use the `document.location.pathname` of the iframe.

I would prefer to use `/` inside of iframes, but I don't know enough about routing to know if this is a bug/limitation/whatever.

**Comment by yoshuawuyts** [comment] 2016-11-29 16:38
Oh that's interesting - not entirely sure what's causing that - I think it might because of how we initialize our base route in https://github.com/yoshuawuyts/sheet-router/blob/master/create-location.js. The 4.x routing patch was intended to make apps / mobile / electron easier to use, I hadn't really considered `iframes` at all so thanks for reporting!

What might work (untested) is setting a base tag so it resolves correctly - https://developer.mozilla.org/en/docs/Web/HTML/Element/base - could you let me know if that perhaps works?

**Comment by johnlindquist** [comment] 2016-11-29 16:53
No luck using the `base` tag.

`<base href="/">` won't even load the script (since the script is hosted in a `/generatedkey` path)

```
<script type="text/javascript">
      document.write("<base href='" + document.location.pathname + "' />");
</script>
```
loads the script, but gives me the same error as before.

**Comment by Ryuno-Ki** [comment] 2016-11-29 17:10
Some tools moarn about base-tag not being a full-qualified URL (with protocol, subdomain and domain). Although absolute or even relative paths are valid according to the spec.

IIRC there were some differences between `window.location`, `document.location` and `document.URL` when it comes to iFrame …

**Comment by yoshuawuyts** [comment] 2017-04-07 16:45
Released https://github.com/yoshuawuyts/microframe recently; think we're close to getting a good set of choo modules wired up in a standalone package aimed to be integrated in other libs. Most things don't need a router, so might as well make it standalone. Sooon :sparkles:

**Comment by yoshuawuyts** [comment] 2017-04-23 20:33
So `choo@6` will solve this completely, where as per #480 we'll be prototype based which means you can set your own `app.router`. So for iframes you could create a simple router that doesn't try and parse `window.location` stuff C:

**Comment by yoshuawuyts** [comment] 2018-01-17 22:46
@goto-bus-stop yep I think so. Closing!

**Closed by yoshuawuyts** 2018-01-17 22:46 UTC
Labels: Type: Question
