### ISSUE TITLE
state.route not updated after navigate event triggered by pushState

### ISSUE THREAD

**Issue by akiva** [choojs/choo#538] opened 2017-07-26 06:19 UTC
### Expected behavior

Expecting to have my subscription to the `navigate` event trigger and report the current (as in _just navigated to_) route in `state.route`

### Actual behavior

I see the initial route reported in the `navigate` listener, ie. showing a `state.route` equal to `/` after I trigger `emit('pushState', '/shazam')` rather than `state.route` equal to `/shazam`. 

### Steps to reproduce behavior

See my gist https://gist.github.com/akiva/fed503aed3a76be6bbf1dada30f9018b, which is using `choo@next`.

**Comment by toddself** [comment] 2017-07-26 16:18
Closing as a dupe of #530  (re-open this if i'm missing something but they seem to be the same issue)

**Closed by toddself** 2017-07-26 16:18 UTC
